repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        types_or: [python]
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        types_or: [python]
      - id: end-of-file-fixer
        types_or: [python]
      - id: check-yaml
        files: .yaml
      - id: check-toml
        files: .toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        types_or: [python]
        additional_dependencies: ["pydantic>=2.5.0"]
